name: mobile
description: A piggybank mobile application

publish_to: 'none'
version: 0.0.0-dev+0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^3.1.0
  protobuf_google: ^0.0.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  auto_route: ^6.0.5
  google_fonts: ^4.0.3
  shared_utils:
    git: https://github.com/quabynah-bilson/shared_utils.git
  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^6.0.3
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/anim/