name: mobile
description: A piggybank mobile application

publish_to: 'none'
version: 0.0.0-dev+0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^3.1.0
  protobuf_google: ^0.0.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  shared_utils:
    git: https://github.com/quabynah-bilson/shared_utils.git
  protobuf: ^2.1.0
  lottie: ^2.3.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_grid_view: ^0.6.2
  flutter_staggered_animations: ^1.1.1
  dartz: ^0.10.1
  flutter_secure_storage: ^8.0.0
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/avatars/
    - assets/anim/

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/app_logo.png"
    background_color: "#FFE7AB"
    theme_color: "#FFE7AB"
  windows:
    generate: true
    image_path: "assets/img/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/app_logo.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/img/app_logo.png
  image_dark: assets/img/app_logo.png
  icon_background_color: "#ffffff"
  color: "#ffffff"
  color_dark: "#ffffff"
  icon_background_color_dark: "#ffffff"
  web: false
  web_image_mode: contain
  android_12:
    image: assets/img/app_logo.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"
    color_dark: "#ffffff"
    image_dark: assets/img/app_logo.png